// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqH4PCc-rs86qYI5ZGwi2WOU4PtMJJzVE',
    appId: '1:6848613159:web:3250e45472fa6762137702',
    messagingSenderId: '6848613159',
    projectId: 'trakradminsetup-28437',
    authDomain: 'trakradminsetup-28437.firebaseapp.com',
    storageBucket: 'trakradminsetup-28437.firebasestorage.app',
    measurementId: 'G-N3M010CSJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjythFVr0CYzT_DFa08Mx9DPmNIwYtKAY',
    appId: '1:6848613159:android:d86d0ba6fd6a190e137702',
    messagingSenderId: '6848613159',
    projectId: 'trakradminsetup-28437',
    storageBucket: 'trakradminsetup-28437.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVEA0racHn3yzu4JWbnJrStwvIo8kleRY',
    appId: '1:6848613159:ios:6b71e30dd1c4eb98137702',
    messagingSenderId: '6848613159',
    projectId: 'trakradminsetup-28437',
    storageBucket: 'trakradminsetup-28437.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVEA0racHn3yzu4JWbnJrStwvIo8kleRY',
    appId: '1:6848613159:ios:6b71e30dd1c4eb98137702',
    messagingSenderId: '6848613159',
    projectId: 'trakradminsetup-28437',
    storageBucket: 'trakradminsetup-28437.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqH4PCc-rs86qYI5ZGwi2WOU4PtMJJzVE',
    appId: '1:6848613159:web:621bd8a599b61a65137702',
    messagingSenderId: '6848613159',
    projectId: 'trakradminsetup-28437',
    authDomain: 'trakradminsetup-28437.firebaseapp.com',
    storageBucket: 'trakradminsetup-28437.firebasestorage.app',
    measurementId: 'G-VJ9FM6QCLR',
  );
}
